const values = {
    "1": "school_details:district",
    "2": "school_details:block",
    "3": "school_details:cluster",
    "4": "school_details:school-name",
    "5": "basic_details:S_Loc:Latitude",
    "6": "basic_details:S_Loc:Longitude",
    "7": "basic_details:S_Loc:Altitude",
    "8": "basic_details:S_Loc:Accuracy",
    "9": "classroom_observation:T_Class",
    "10": "classroom_observation:T_LOs",
    "11": "classroom_observation:T_FAs",
    "12": "classroom_observation:FA_Image",
    "13": "classroom_observation:T_Tdprep",
    "14": "classroom_observation:T_LF_ABL",
    "15": "classroom_observation:T_Recommend",
    "16": "classroom_observation:Overall_feedback_reason:T_Recommend_Name",
    "17": "classroom_observation:Overall_feedback_reason:T_Recommend_Reason",
    "18": "assessment:CCE_Records:Assess_CCE",
    "19": "assessment:Spot_Assessment:SA_Stud1",
    "20": "assessment:Spot_Assessment:SA_Stud2",
    "21": "assessment:Spot_Assessment:SA_Stud3",
    "22": "Academic_interventions:LO_Charts",
    "23": "Academic_interventions:LOCharts_Image",
    "24": "Academic_interventions:PrernaPrayas_Mat",
    "25": "Academic_interventions:PrernaPrayas_Usage",
    "26": "Academic_interventions:Samaprk_Usage",
    "27": "Academic_interventions:NCERTKits",
    "28": "Academic_interventions:BarkhaSeries",
    "29": "Academic_interventions:LOQuestBank_Usage",
    "30": "Academic_interventions:RT_Use",
    "31": "Academic_interventions:CHT_Meeting",
    "32": "Academic_interventions:Assess_Dash_Usage",
    "33": "Academic_interventions:Assess_Dash_paste",
    "34": "Academic_interventions:Assess_Dash_image",
    "35": "Academic_interventions:Tech_WA",
    "36": "Academic_interventions:Tech_OnlineResource",
    "37": "Academic_interventions:Tech_KS",
    "38": "Academic_interventions:Tech_KS_Reason",
    "39": "Academic_interventions:Innovation",
    "40": "Academic_interventions:Inn_Ex",
};

module.exports = values;